# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Genre')),
            ],
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='is_active',
        ),
        migrations.AddField(
            model_name='music',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Tracks'),
        ),
    ]
