# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-26 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_auto_20170426_0942'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['-track_id'],
            },
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.Genre'),
        ),
        migrations.AddField(
            model_name='music',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Tracks'),
        ),
    ]
