# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-16 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170416_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='music',
            name='track',
        ),
        migrations.AddField(
            model_name='tracks',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Genre'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
