# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-17 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170417_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
