# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-18 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_auto_20170418_1818'),
        ('music', '0006_auto_20170417_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.Genre')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Tracks')),
            ],
        ),
    ]
