# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-26 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
    ]
